# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bedbb8f6ea67694da2eb9b7eca6794a31ef4ad7927fb17b57f40cf6e4a0499878861a59963f3f71769d0d29559113b852980ce62ad84d13af7bb2a1b5b3ebcf0

test:
  secret_key_base: eccf437cd16d4402df97ed8d061d564a3a133f121d4bf3fed12793b767c1d44c73fd455bcb2f0eb5051c20fd2e3271ca6b559a6e748ffd57b88206411d442a6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
